log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: "traefik_default"
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true
    
tls:
  certificates:
    - certFile: "/etc/traefik/cert/bff.localhost.crt"
      keyFile: "/etc/traefik/cert/bff.localhost.key"
    - certFile: "/etc/traefik/cert/vape.localhost.crt"
      keyFile: "/etc/traefik/cert/vape.localhost.key"
